Repository Team1-CodeIt-Sprint6/K-venture, pull requests merged in 2024-08, with the labels that each got.

#15 [GN-65] feat: 헤더 컴포넌트 추가
  public/assets/icons/icon_notification.svg
  public/assets/icons/icon_profile.svg
  public/assets/icons/logo_big.svg
  public/assets/icons/logo_lg.svg
  public/assets/icons/logo_md.svg
  public/assets/icons/logo_small.svg
  public/assets/icons/symbol.svg
  src/components/common/HeaderUserProfile.tsx
  src/components/layout/Header.tsx
Labels: 🍀feat

#13 [GN-41] feat: 이미지 인풋 컴포넌트 구현 및 반응형 디자인
  public/assets/icons/icon_plus.svg
  src/components/MyActivityPage/ImageInput.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: 🍀feat

#7 [GN-18] feat: 달력 컴포넌트 추가
  eslint.config.mjs
  package.json
  public/assets/icons/icon_calendar_input.svg
  src/components/common/DatePicker/CalendarInput.tsx
  src/components/common/DatePicker/DatePicker.tsx
  src/components/common/DatePicker/DayMarker.tsx
  src/components/common/DatePicker/InlineDateSection.tsx
  src/components/common/DatePicker/PopupDateSection.tsx
  src/components/common/DatePicker/getCommonDatePickerProps.ts
  src/constants/datePickerConstants.ts
  src/hooks/useCalender.ts
  src/lib/utils/foramtDate.ts
  src/styles/globals.css
  yarn.lock
Labels: 🍀feat

#11 [GN-87] feat: 입력 관련 컴포넌트 추가
  public/static/PretendardVariable.woff2
  src/components/common/Button.tsx
  src/components/common/ErrorText.tsx
  src/components/common/Input.tsx
  src/components/common/Label.tsx
  src/pages/_app.tsx
  src/pages/login/index.tsx
  tailwind.config.ts
Labels: 🍀feat

#17 [GN 92] feat: 프로필 이미지 인풋 컴포넌트 구현
  public/assets/icons/icon_pen.svg
  public/assets/images/main_banner.png
  public/assets/images/profile_default_img.png
  src/components/common/LeftNavBar.tsx
  src/components/userProfile/UploadProfile.tsx
  yarn.lock
Labels: 🍀feat

#14 [GN-42] feat: 이미지 카드 컴포넌트 구현
  public/assets/icons/icon_x_red.svg
  src/components/MyActivityPage/ImageCard.tsx
  src/components/MyActivityPage/ImageInput.tsx
  src/styles/globals.css
Labels: 🍀feat

#12 [GN-94] feat: tanstack-query 설정
  package.json
  src/hooks/useFetchData.ts
  src/hooks/useHooks.ts
  src/pages/_app.tsx
  yarn.lock
Labels: 🍀feat

#20 [GN-95] feat: axios 기본 설정과 로그인 로직 구현
  .gitignore
  package.json
  src/hooks/useLogin.ts
  src/lib/apis/axios.ts
  src/lib/apis/postApis.ts
  src/pages/logintest.tsx
  src/styles/globals.css
  src/types/post/loginTypes.ts
  src/types/userTypes.ts
  tailwind.config.ts
  yarn.lock
Labels: 🍀feat

#16 [GN-73] feat: 공통 모달 컴포넌트 추가
  eslint.config.mjs
  package.json
  public/assets/icons/icon_check.svg
  src/components/common/Button.tsx
  src/components/common/Modal/CustomModals/AlertModal.tsx
  src/components/common/Modal/CustomModals/ConfirmModal.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/ModalContainer.tsx
  src/components/common/Modal/index.tsx
  src/constants/modalConstants.ts
  src/hooks/useModal.ts
  src/pages/logintest.tsx
  src/styles/globals.css
  src/types/Modaltypes.ts
  tailwind.config.ts
Labels: 🍀feat

#19 [GN- 104] feat: 레이아웃 추가
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/MainLayout.tsx
  src/pages/_app.tsx
  src/styles/globals.css
Labels: 🍀feat

#18 [GN-96] fix: husky 스크립트와 git 커맨드 충돌 해결
  .husky/prepare-commit-msg
Labels: 🛠️fix

#23 [GN 69] feat: 로그인 페이지 구현
  package.json
  public/assets/icons/icon_noshow_password.svg
  public/assets/icons/icon_show_password.svg
  public/assets/icons/logo_big_mobile.svg
  src/components/Auth/AuthLayout.tsx
  src/components/Auth/AuthLayoutFooter.tsx
  src/components/Auth/AuthLayoutHeader.tsx
  src/components/Auth/LoginForm.tsx
  src/components/Auth/PasswordInput.tsx
  src/components/common/Input.tsx
  src/constants/windowSize.ts
  src/pages/login/index.tsx
  src/pages/logintest.tsx
  yarn.lock
Labels: 🍀feat

#28 [GN-43] feat: 이미지 관리 컴포넌트 완성 (+ 레이아웃 너비 최솟값 지정)
  src/components/MyActivityPage/ImageCard.tsx
  src/components/MyActivityPage/ImageInput.tsx
  src/components/MyActivityPage/ImageList.tsx
  src/components/MyActivityPage/MyActivityForm.tsx
  src/constants/myActivityPage.ts
  src/hooks/useImagesHandler.ts
  src/pages/_app.tsx
  src/pages/my-activity/index.tsx
  src/styles/globals.css
  src/types/activityTypes.ts
  src/types/page/myActivityPageTypes.ts
  tailwind.config.ts
Labels: 🍀feat

#21 [GN-111] feat: 헤더 유저정보 연결, 전역 인증상태 관리
  package.json
  src/components/layout/Header.tsx
  src/components/layout/MainLayout.tsx
  src/lib/apis/axios.ts
  src/lib/apis/postApis.ts
  src/lib/apis/userApis.ts
  src/state/auth.ts
  src/styles/globals.css
  yarn.lock
Labels: 🍀feat

#32 [GN-116] fix: 헤더 데이터 패칭 조정, 하이드레이션 오류 수정
  src/components/layout/Header.tsx
  src/hooks/useFetchData.ts
  src/styles/globals.css
Labels: 🛠️fix

#29 [GN-46] style: 스케줄 확인 및 제거 가능한 스케줄 컴포넌트 완성
  public/assets/icons/icon_minus.svg
  src/components/MyActivityPage/MyActivityForm.tsx
  src/components/MyActivityPage/Schedule.tsx
  src/lib/utils/formatDate.ts
  src/styles/globals.css
  tailwind.config.ts
Labels: 🍀feat

#30 [GN-43] refactor: useImageManager에서 렌더링까지 맡도록 변경
  src/components/MyActivityPage/ImageList.tsx
  src/components/MyActivityPage/MyActivityForm.tsx
  src/hooks/useImageManager.tsx
  src/hooks/useImagesHandler.ts
Labels: 🍀feat

#31 [GN-115] feat: 값 선택 드롭다운 컴포넌트
  public/assets/icons/icon_dropdown.svg
  src/components/common/Dropdown/ValueDropdown.tsx
  src/hooks/useDropdown.ts
  src/styles/globals.css
  tailwind.config.ts
Labels: 🍀feat

#22 [GN 71] feat: 프로필 정보 업데이트 구현
  .gitignore
  next.config.mjs
  package.json
  src/components/common/LeftNavBar.tsx
  src/components/layout/MainLayout.tsx
  src/components/userProfile/EditProfileForm.tsx
  src/components/userProfile/EditProfileImage.tsx
  src/components/userProfile/UploadProfile.tsx
  src/lib/apis/patchApis.ts
  src/lib/apis/postApis.ts
  src/lib/apis/putApis.ts
  src/lib/apis/userApis.ts
  src/pages/profile.tsx
  src/styles/globals.css
  src/types/userTypes.ts
  tailwind.config.ts
  yarn.lock
Labels: 🍀feat

#34 [GN-48] feat: 스케줄 관리 컴포넌트 구현 및 적용
  public/assets/icons/icon_plus_blue.svg
  src/components/MyActivityPage/MyActivityForm.tsx
  src/components/MyActivityPage/Schedule.tsx
  src/components/MyActivityPage/ScheduleInput.tsx
  src/components/MyActivityPage/ScheduleList.tsx
  src/constants/myActivityPage.ts
  src/hooks/useDropdown.ts
  src/lib/utils/myActivityPage.ts
  src/styles/globals.css
Labels: 🍀feat

#36 [GN-39] feat: 내 체험 페이지 제작
  package.json
  src/components/MyActivityPage/ImageCard.tsx
  src/components/MyActivityPage/MyActivityForm.tsx
  src/lib/apis/postApis.ts
  src/lib/apis/putApis.ts
  src/styles/globals.css
  src/types/activityTypes.ts
  src/types/modalTypes.ts
  src/types/post/uploadImageTypes.ts
  yarn.lock
Labels: 🍀feat

#37 [GN-119] feat: 토큰 재발급
  src/hooks/useLogin.ts
  src/lib/apis/postApis.ts
Labels: 🍀feat

#33 [GN 97] feat: 체험 상세 페이지(타이틀, 설명, 케밥) 구현
  eslint.config.mjs
  public/assets/icons/icon_kebab.svg
  public/assets/icons/icon_location.svg
  public/assets/icons/icon_star.svg
  src/components/activity/CustomKebab.tsx
  src/components/activity/Location.tsx
  src/components/activity/Review.tsx
  src/components/common/Kebab/KebabContainer.tsx
  src/components/common/Kebab/KebabDelete.tsx
  src/components/common/Kebab/KebabLink.tsx
  src/components/common/Modal/Modal.tsx
  src/components/userProfile/EditProfileImage.tsx
  src/hooks/useModal.ts
  src/lib/apis/deleteApis.ts
  src/lib/apis/getApis.ts
  src/lib/apis/postApis.ts
  src/pages/activity/[id].tsx
  src/styles/globals.css
  src/types/activityTypes.ts
  src/types/errorTypes.ts
  src/types/kebabTypes.ts
  tailwind.config.ts
Labels: 🍀feat

#44 [GN-122] fix: 모달 콜백함수 인터페이스 추가
  src/components/ActivityPage/ReservationCard/DesktopReservationCard/index.tsx
  src/components/ActivityPage/ReservationCard/MobileReservationCard/ReservationFooterMenu.tsx
  src/components/ActivityPage/ReservationCard/TabletReservationCard/Step3TabletCard.tsx
  src/components/ActivityPage/ReservationCard/index.tsx
  src/components/MyActivityPage/MyActivityForm.tsx
  src/components/activity/CustomKebab.tsx
  src/components/common/Modal/CustomModals/AlertModal.tsx
  src/components/common/Modal/CustomModals/ConfirmModal.tsx
  src/components/common/Modal/Modal.tsx
  src/components/userProfile/EditProfileForm.tsx
  src/constants/modalConstants.ts
  src/hooks/useModal.ts
  src/types/modalTypes.ts
  tsconfig.json
Labels: 🛠️fix

#45 [GN 98] feat: 체험 상세 배너 이미지 구현
  package.json
  src/components/activity/ImageGallery.tsx
  src/components/activity/ImageSlider.tsx
  src/lib/apis/getApis.ts
  src/lib/utils/activityImageUtils.ts
  src/lib/utils/gridUtils.ts
  src/lib/utils/swiperConfig.ts
  src/lib/utils/utils.ts
  src/pages/activity/[id].tsx
  src/styles/globals.css
  src/types/activityTypes.ts
  yarn.lock
Labels: 🍀feat

#49 [GN-125] fix: 배포 오류 수정
  src/components/common/DatePicker/InlineDateSection.tsx
  src/components/common/DatePicker/PopupDateSection.tsx
  src/components/common/DatePicker/getCommonDatePickerProps.ts
Labels: 🛠️fix

#48 [GN-25] feat: 예약현황 데이터 달력에 표시 기능 추가
  src/hooks/useDropdown.ts
  src/hooks/useReservationCalendar.tsx
  src/hooks/useReservationDashboardData.ts
  src/lib/apis/getApis.ts
  src/lib/utils/formatDate.ts
  src/pages/reservation-dashboard/index.tsx
  src/state/reservationDashboardAtom.ts
  src/styles/globals.css
Labels: 🍀feat

#47 [GN-100] feat: 체험 상세 지도 구현
  package.json
  public/assets/icons/icon_symbol.svg
  public/favicon.ico
  src/components/activity/ImageGallery.tsx
  src/components/activity/ImageSlider.tsx
  src/components/activity/KakaoMap.tsx
  src/components/activity/Location.tsx
  src/components/activity/Review.tsx
  src/components/common/Kebab/KebabContainer.tsx
  src/lib/apis/getApis.ts
  src/lib/utils/activityImageUtils.ts
  src/lib/utils/gridUtils.ts
  src/pages/_document.tsx
  src/pages/activity/[id].tsx
  src/styles/globals.css
  tsconfig.json
  yarn.lock
Labels: 🍀feat

#50 [GN-16] feat: 예약내역 페이지 내 예약 리스트
  public/assets/images/empty_img.png
  src/components/MyReservationsPage/MyReservationList.tsx
  src/components/common/ActivityCard/MyCardLayout.tsx
  src/components/common/ActivityCard/MyReservationCard.tsx
  src/components/common/Dropdown/SortDropdown.tsx
  src/components/layout/MainLayout.tsx
  src/hooks/useInfiniteScroll.ts
  src/lib/apis/getApis.ts
  src/lib/apis/patchApis.ts
  src/pages/my-reservations/index.tsx
Labels: 🍀feat

#54 [GN-27] feat: 후기 작성 모달 추가
  public/assets/icons/icon_star_off.svg
  public/assets/icons/icon_star_on.svg
  src/components/MyReservationsPage/MyReservationList.tsx
  src/components/MyReservationsPage/StarRating.tsx
  src/components/common/Modal/CustomModals/ReviewModal.tsx
  src/components/common/Modal/Modal.tsx
  src/hooks/useModal.ts
  src/lib/apis/postApis.ts
  src/types/modalTypes.ts
  src/types/post/reviewTypes.ts
Labels: 🍀feat

#53 [GN-51] feat: 예약 정보 모달 데이터 로직 구현
  src/components/ReservationDashboardPage/DailyReservationModal.tsx
  src/hooks/useDailyReservationData.ts
  src/hooks/useDropdown.ts
  src/hooks/useReservationCalendar.tsx
  src/hooks/useReservationDashboardData.ts
  src/lib/apis/getApis.ts
  src/pages/reservation-dashboard/index.tsx
  src/state/reservationDashboardAtom.ts
  src/styles/globals.css
  src/types/get/ReservationDashboardPageGetTypes.ts
  src/types/page/ReservationDashboardPageTypes.ts
Labels: 🍀feat

#56 [GN-129] fix: 체험 등록 버그 및 스타일 수정
  src/components/MyActivityPage/ImageInput.tsx
  src/components/MyActivityPage/MyActivityForm.tsx
  src/components/MyActivityPage/Schedule.tsx
  src/components/MyActivityPage/ScheduleInput.tsx
  src/components/common/DatePicker/CalendarInput.tsx
  src/components/common/Dropdown/ValueDropdown.tsx
  src/styles/globals.css
  src/types/activityTypes.ts
Labels: 🛠️fix

#59 [GN-54] feat: 예약 내역, 상태탭 컴포넌트 추가
  package.json
  src/components/ActivityPage/ReservationCard/DesktopReservationCard/index.tsx
  src/components/ReservationDashboardPage/DailyReservationModal.tsx
  src/components/ReservationDashboardPage/DailyReservationModal/DailyReservationDateDropdown.tsx
  src/components/ReservationDashboardPage/DailyReservationModal/DailyReservationList.tsx
  src/components/ReservationDashboardPage/DailyReservationModal/DailyReservationTaps.tsx
  src/components/ReservationDashboardPage/DailyReservationModal/index.tsx
  src/components/ReservationDashboardPage/ReservationDashboardDropdown.tsx
  src/constants/dailyReservationModalConstants.ts
  src/hooks/useDailyReservationData.ts
  src/hooks/useReservation.ts
  src/hooks/useReservationCalendar.tsx
  src/hooks/useReservationDashboardData.ts
  src/hooks/useUpdateReservationStatus.ts
  src/lib/apis/getApis.ts
  src/lib/apis/patchApis.ts
  src/state/reservationDashboardAtom.ts
  src/styles/globals.css
  src/types/page/ReservationDashboardPageTypes.ts
  tailwind.config.ts
  yarn.lock
Labels: 🍀feat

#58 [GN-21] feat: 내 체험 관리 페이지 추가
  src/components/MyActivitiesPage/MyActivityList.tsx
  src/components/MyReservationsPage/MyReservationList.tsx
  src/components/common/ActivityCard/MyActivityCard.tsx
  src/components/common/Modal/CustomModals/ReviewModal.tsx
  src/hooks/useInfiniteScroll.ts
  src/hooks/useInfiniteScrollActivity.ts
  src/hooks/useInfiniteScrollHandler.ts
  src/hooks/useInfiniteScrollReservation.ts
  src/lib/apis/getApis.ts
  src/pages/my-activities/index.tsx
  src/styles/globals.css
  src/types/get/reservationTypes.ts
  src/types/myActivitiesTypes.ts
Labels: 🍀feat

#60 [GN-132] feat: 예약 정보 모달에 무한스크롤 추가
  public/assets/icons/icon_arrow_down.svg
  public/assets/icons/icon_x_lg.svg
  src/components/ActivityPage/ReservationCard/ReservationCommon/ReservationHeader.tsx
  src/components/ReservationDashboardPage/DailyReservationModal/DailyReservationDateDropdown.tsx
  src/components/ReservationDashboardPage/DailyReservationModal/DailyReservationList.tsx
  src/components/ReservationDashboardPage/DailyReservationModal/DailyReservationModalHeader.tsx
  src/components/ReservationDashboardPage/DailyReservationModal/DailyReservationTaps.tsx
  src/components/ReservationDashboardPage/DailyReservationModal/index.tsx
  src/components/common/InfiniteScrollHint.tsx
  src/components/common/Modal/CustomModals/ReviewModal.tsx
  src/components/common/Modal/ModalContainer.tsx
  src/constants/dailyReservationModalConstants.ts
  src/hooks/useDailyReservationData.ts
  src/hooks/useDailyReservationListInfinite.ts
  src/hooks/useDropdown.ts
  src/hooks/useReservationCalendar.tsx
  src/hooks/useReservationDashboardData.ts
  src/hooks/useScrollLock.ts
  src/lib/apis/getApis.ts
  src/pages/reservation-dashboard/index.tsx
  src/styles/globals.css
  src/types/get/ReservationDashboardPageGetTypes.ts
Labels: 🍀feat

#61 [GN-55] feat: 알림 기능 구현
  src/components/layout/Header.tsx
  src/components/myNotificatons/Notification.tsx
  src/components/myNotificatons/NotificationModal.tsx
  src/hooks/useNotificationsInfinite.ts
  src/lib/apis/deleteApis.ts
  src/lib/apis/getApis.ts
  src/styles/globals.css
  src/types/NotificationTypes.ts
Labels: 🍀feat

#63 [GN-156] fix: 승인,거절 요청 후 리스트 재랜더링 추가
  src/components/ReservationDashboardPage/DailyReservationModal/DailyReservationList.tsx
  src/hooks/useDailyReservationListInfinite.ts
Labels: 🛠️fix

#65 [GN-134] feat: 로그인 상태 헤더에 프로필 메뉴 추가
  public/assets/icons/icon_gear.svg
  public/assets/icons/icon_list.svg
  public/assets/icons/icon_user.svg
  src/components/common/LeftNavBar.tsx
  src/components/layout/Header.tsx
  src/components/layout/ProfileMenu.tsx
  src/components/myNotificatons/NotificationModal.tsx
  src/lib/utils/logout.ts
  src/pages/profile-menu.tsx
  src/pages/profile.tsx
  src/styles/globals.css
  yarn.lock
Labels: 🍀feat, 💭refact

#66 [GN-158] refactor: 로그인/회원가입 에러 스키마 및 스타일 개선
  src/components/Auth/LoginForm.tsx
  src/components/Auth/PasswordInput.tsx
  src/components/Auth/SignupForm.tsx
  src/components/common/Input.tsx
  src/lib/utils/authSchema.ts
  src/pages/login.tsx
  src/pages/signup.tsx
  src/state/auth.ts
  src/styles/globals.css
Labels: 💭refact

#67 [GN-103] refactor: 모달 등장 효과 추가
  src/components/ReservationDashboardPage/DailyReservationModal/index.tsx
  src/components/common/Modal/Modal.tsx
  src/components/layout/Header.tsx
  src/components/layout/LayoutContainer.tsx
  src/pages/reservation-dashboard/index.tsx
  tailwind.config.ts
Labels: 💭refact

#68 [GN-155] refactor: 예약 현황 모달 모바일 레이아웃 수정
  src/components/ActivityPage/ReservationCard/MobileReservationCard/ReservationFooterMenu.tsx
  src/components/ActivityPage/ReservationCard/MobileReservationCard/ReservationModal.tsx
  src/components/ActivityPage/ReservationCard/ReservationCommon/DateTimeSummary.tsx
  src/components/ReservationDashboardPage/DailyReservationModal/DailyReservationDateDropdown.tsx
  src/components/ReservationDashboardPage/DailyReservationModal/DailyReservationList.tsx
  src/components/ReservationDashboardPage/DailyReservationModal/DailyReservationModalHeader.tsx
  src/components/ReservationDashboardPage/DailyReservationModal/DailyReservationTaps.tsx
  src/components/ReservationDashboardPage/DailyReservationModal/index.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/ModalContainer.tsx
  src/components/layout/MainLayout.tsx
  src/hooks/useReservationCalendar.tsx
  src/styles/globals.css
Labels: 🛠️fix

#70 [GN-165] fix: 체험 상세 별점 및 주소 아이콘 위치 수정
  src/components/activity/Location.tsx
  src/components/activity/Review.tsx
  src/pages/activity/[id].tsx
Labels: 🛠️fix

#73 [GN-167] fix: 401 리다이렉트 위한 모달 로직 추가
  public/assets/images/blue_wave.png
  public/assets/images/red_wave.png
  src/components/layout/MainLayout.tsx
  src/components/layout/PageWithLnb.tsx
  src/constants/routeConstants.ts
  src/pages/404.tsx
  tailwind.config.ts
Labels: 🛠️fix

#75 [GN-157] feat: 체험상세 예약모달 개선
  src/components/ActivityPage/ReservationCard/MobileReservationCard/Step1MobileCard.tsx
  src/components/activity/ReservationCard/DesktopReservationCard/index.tsx
  src/components/activity/ReservationCard/MobileReservationCard/ReservationFooterMenu.tsx
  src/components/activity/ReservationCard/MobileReservationCard/ReservationModal.tsx
  src/components/activity/ReservationCard/MobileReservationCard/Step1MobileCard.tsx
  src/components/activity/ReservationCard/MobileReservationCard/Step2MobileCard.tsx
  src/components/activity/ReservationCard/MobileReservationCard/index.tsx
  src/components/activity/ReservationCard/ReservationCommon/ContentTitle.tsx
  src/components/activity/ReservationCard/ReservationCommon/DateTimeSummary.tsx
  src/components/activity/ReservationCard/ReservationCommon/ParticipantCounter.tsx
  src/components/activity/ReservationCard/ReservationCommon/PriceDisplay.tsx
  src/components/activity/ReservationCard/ReservationCommon/ReservationButton.tsx
  src/components/activity/ReservationCard/ReservationCommon/ReservationHeader.tsx
  src/components/activity/ReservationCard/ReservationCommon/SelectDateTextButton.tsx
  src/components/activity/ReservationCard/ReservationCommon/TimeSelector.tsx
  src/components/activity/ReservationCard/ReservationCommon/TotalSummary.tsx
  src/components/activity/ReservationCard/TabletReservationCard/Step1TabletCard.tsx
  src/components/activity/ReservationCard/TabletReservationCard/Step2TabletCard.tsx
  src/components/activity/ReservationCard/TabletReservationCard/Step3TabletCard.tsx
  src/components/activity/ReservationCard/TabletReservationCard/index.tsx
  src/components/activity/ReservationCard/index.tsx
  src/components/common/DatePicker/BookingDot.tsx
  src/components/common/DatePicker/DatePicker.tsx
  src/components/common/DatePicker/DayMarker.tsx
  src/components/common/DatePicker/InlineDateSection.tsx
  src/components/common/DatePicker/PopupDateSection.tsx
  src/hooks/useActivityDetail.ts
  src/hooks/useReservation.ts
  src/pages/activity/[id].tsx
  src/styles/globals.css
  src/types/activityDetailPageTypes.ts
Labels: 🍀feat, 🛠️fix

#72 [GN-138] fix: 예약 내역, 내 체험 관리 페이지 수정
  public/assets/icons/icon_star_off.svg
  public/assets/images/default_img.png
  src/components/MyActivitiesPage/MyActivityList.tsx
  src/components/MyReservationsPage/MyReservationList.tsx
  src/components/MyReservationsPage/StarRating.tsx
  src/components/common/ActivityCard/MyActivityCard.tsx
  src/components/common/ActivityCard/MyCardLayout.tsx
  src/components/common/EmptyState.tsx
  src/components/common/Modal/CustomModals/ReviewModal.tsx
  src/components/layout/Footer.tsx
  src/styles/globals.css
Labels: 🛠️fix

#74 [GN-150] fix: 체험등록 인풋, 시간 선택 수정
  src/components/MyActivityEditPage/MyActivityEditForm.tsx
  src/components/MyActivityPage/MyActivityForm.tsx
  src/lib/utils/activityFormSchema.ts
  src/lib/utils/myActivityPage.ts
  src/styles/globals.css
Labels: 🛠️fix

#71 feat: 메인 페이지 일부 완성
  public/assets/icons/icon_search.svg
  public/assets/icons/icon_star_md.svg
  src/components/Main/ActivityCategory.tsx
  src/components/Main/BestExperienceCard.tsx
  src/components/Main/BestExperienceList.tsx
  src/components/Main/ExperienceCard.tsx
  src/components/Main/ExperienceList.tsx
  src/components/Main/ExperienceListNavBar.tsx
  src/components/Main/MainBannerSection.tsx
  src/components/Main/MainListSection.tsx
  src/components/Main/MainPageLayout.tsx
  src/components/Main/MainPagination.tsx
  src/hooks/useActivityList.ts
  src/hooks/useImageLoad.ts
  src/hooks/useLogin.ts
  src/lib/apis/getApis.ts
  src/lib/utils/splitArray.ts
  src/pages/index.tsx
  src/state/activityListAtom.ts
  src/types/activityTypes.ts
  src/types/get/activityTypes.ts
Labels: 🍀feat

#76 [GN-164] feat: 예약 현황 페이지에서 예약 현황 없는 경우 처리
  src/components/Main/ActivityCategory.tsx
  src/components/ReservationDashboardPage/NoReservationsState.tsx
  src/components/ReservationDashboardPage/ReservationDashboardHeader.tsx
  src/pages/reservation-dashboard/index.tsx
  src/styles/globals.css
Labels: 🍀feat

#77 [GN-118] fix: 팝업 달력 위치 수정
  src/components/common/DatePicker/PopupDateSection.tsx
  src/styles/globals.css
Labels: 🛠️fix

#78 [GN-175] fix: 체험상세 예약 진행 도중 닫기 버튼 버그 수정
  src/hooks/useCardEventHandler.ts
Labels: 🛠️fix

#79 [GN-163] feat: 로딩 아이콘 추가
  package.json
  public/assets/icons/icon_loading.json
  src/components/MyActivitiesPage/MyActivityList.tsx
  src/components/MyReservationsPage/MyReservationList.tsx
  src/components/ReservationDashboardPage/DailyReservationModal/DailyReservationList.tsx
  src/components/common/Loading.tsx
  src/components/common/Modal/CustomModals/ReviewModal.tsx
  src/components/layout/Header.tsx
  src/components/myNotificatons/NotificationModal.tsx
  src/components/userProfile/EditProfileImage.tsx
  yarn.lock
Labels: 💭refact

#80 [GN-128] fix: 체험 상세 에러 이미지 및 로딩중 처리
  src/components/activity/ImageGallery.tsx
  src/components/activity/ImageSlider.tsx
  src/components/activity/ReservationCard/TabletReservationCard/Step1TabletCard.tsx
  src/components/skeletons/ActivityPageSkeleton.tsx
  src/constants/defaultAssets.ts
  src/hooks/useFetchData.ts
  src/hooks/usePagination.ts
  src/pages/activity/[id].tsx
  src/styles/globals.css
Labels: 🛠️fix, 💭refact

#81 feat(GN-169): 피드백 반영 완료
  src/components/Main/ExperienceListNavBar.tsx
  src/components/Main/MainBannerSection.tsx
  src/lib/utils/checkUnicode.ts
Labels: 🛠️fix

#82 [GN-177] refactor: 체험 상세 렌더링 소요 시간 감소
  src/components/activity/Review.tsx
  src/components/common/ActivityCard/MyActivityCard.tsx
  src/lib/utils/formattedRating.ts
  src/pages/activity/[id].tsx
Labels: 🛠️fix, 💭refact

#87 [GN-172] 메인 페이지 레이아웃 관련 QA
  public/assets/icons/icon_no_list.svg
  src/components/Main/ActivityCategory.tsx
  src/components/Main/BestExperienceCard.tsx
  src/components/Main/BestExperienceList.tsx
  src/components/Main/ExperienceCard.tsx
  src/components/Main/ExperienceList.tsx
  src/components/Main/ExperienceListNavBar.tsx
  src/components/Main/MainBannerSection.tsx
  src/components/Main/MainListSection.tsx
  src/constants/windowSize.ts
Labels: 🛠️fix

#85 [GN-179] fix: 체험 상세 페이지, 후기 모달 수정
  src/components/ActivityPage/ReservationCard/DesktopReservationCard/index.tsx
  src/components/ActivityPage/ReservationCard/MobileReservationCard/ReservationFooterMenu.tsx
  src/components/ActivityPage/ReservationCard/MobileReservationCard/ReservationModal.tsx
  src/components/ActivityPage/ReservationCard/MobileReservationCard/Step1MobileCard.tsx
  src/components/ActivityPage/ReservationCard/MobileReservationCard/Step2MobileCard.tsx
  src/components/ActivityPage/ReservationCard/MobileReservationCard/index.tsx
  src/components/ActivityPage/ReservationCard/ReservationCommon/ContentTitle.tsx
  src/components/ActivityPage/ReservationCard/ReservationCommon/DateTimeSummary.tsx
  src/components/ActivityPage/ReservationCard/ReservationCommon/ParticipantCounter.tsx
  src/components/ActivityPage/ReservationCard/ReservationCommon/PriceDisplay.tsx
  src/components/ActivityPage/ReservationCard/ReservationCommon/ReservationButton.tsx
  src/components/ActivityPage/ReservationCard/ReservationCommon/ReservationHeader.tsx
  src/components/ActivityPage/ReservationCard/ReservationCommon/SelectDateTextButton.tsx
  src/components/ActivityPage/ReservationCard/ReservationCommon/TimeSelector.tsx
  src/components/ActivityPage/ReservationCard/ReservationCommon/TotalSummary.tsx
  src/components/ActivityPage/ReservationCard/TabletReservationCard/Step1TabletCard.tsx
  src/components/ActivityPage/ReservationCard/TabletReservationCard/Step2TabletCard.tsx
  src/components/ActivityPage/ReservationCard/TabletReservationCard/Step3TabletCard.tsx
  src/components/ActivityPage/ReservationCard/TabletReservationCard/index.tsx
  src/components/ActivityPage/ReservationCard/index.tsx
  src/components/MyReservationsPage/StarRating.tsx
  src/components/activity/ReservationCard/MobileReservationCard/ReservationModal.tsx
  src/components/activity/ReservationCard/MobileReservationCard/Step1MobileCard.tsx
  src/components/common/Modal/CustomModals/ReviewModal.tsx
  src/pages/activity/[id].tsx
  src/styles/globals.css
Labels: 🛠️fix

#86 [GN-181] fix: 체험명 드롭다운의 체험명이 긴 경우 처리
  src/components/ReservationDashboardPage/ReservationDashboardDropdown.tsx
Labels: 🛠️fix

#89 [GN-176] fix: 헤더, 후기작성 모달 모바일 버전 수정
  src/components/MyReservationsPage/StarRating.tsx
  src/components/common/HeaderUserProfile.tsx
  src/components/common/Modal/CustomModals/ReviewModal.tsx
Labels: 🛠️fix

#88 [GN-182] fix: 예약 상세 페이지의 예약 모달 UI 수정
  src/components/activity/ReservationCard/DesktopReservationCard/index.tsx
  src/components/activity/ReservationCard/MobileReservationCard/ReservationModal.tsx
  src/components/activity/ReservationCard/ReservationCommon/TimeSelector.tsx
  src/components/activity/ReservationCard/TabletReservationCard/Step2TabletCard.tsx
  src/components/activity/ReservationCard/TabletReservationCard/Step3TabletCard.tsx
  src/components/activity/ReservationCard/TabletReservationCard/index.tsx
  src/styles/globals.css
Labels: 🛠️fix

#90 [GN-183] 배포 서버 내 빌드 에러에 따른 헤더/푸터 내 SVG 파일 호출 방법 변경
  src/components/common/HeaderUserProfile.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/pages/login.tsx
  src/pages/signup.tsx
Labels: 💭refact

#93 [GN-187] fix: 모바일 프로필 레이아웃 수정
  public/assets/icons/icon_dropdown.svg
  public/assets/icons/icon_minus.svg
  public/assets/icons/icon_plus.svg
  public/assets/icons/icon_plus_blue.svg
  public/assets/icons/icon_x_red.svg
  src/components/MyActivityPage/ImageCard.tsx
  src/components/MyActivityPage/ImageInput.tsx
  src/components/MyActivityPage/Schedule.tsx
  src/components/MyActivityPage/ScheduleInput.tsx
  src/components/ReservationDashboardPage/ReservationDashboardDropdown.tsx
  src/components/common/Modal/ModalContainer.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/ProfileMenu.tsx
  src/components/userProfile/EditProfileForm.tsx
  src/components/userProfile/EditProfileImage.tsx
  src/pages/profile-menu.tsx
  src/state/profileAtom.ts
Labels: 🛠️fix, 💭refact

#94 [GN-189] Fix: 메인 페이지 내 옵션 관련 버그 및 배너 디자인 적용
  src/components/Auth/AuthLayoutHeader.tsx
  src/components/Main/ActivityCategory.tsx
  src/components/Main/BestExperienceCard.tsx
  src/components/Main/BestExperienceList.tsx
  src/components/Main/ExperienceCard.tsx
  src/components/Main/ExperienceList.tsx
  src/components/Main/MainBannerSection.tsx
  src/components/layout/Header.tsx
  src/styles/globals.css
Labels: 🛠️fix

#96 [GN-188] fix: 체험 상세 예약 모달 수정
  src/components/activity/ReservationCard/ReservationCommon/TimeSelector.tsx
Labels: 🛠️fix
